// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(SorteioContext))]
    partial class SorteioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sorteio.Domain.Criterios.ResultadoDaAvaliacaoDosCriterios", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataDeSelecao")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId")
                        .IsUnique()
                        .HasFilter("[FamiliaId] IS NOT NULL");

                    b.ToTable("ResultadosDaAvaliacaoDosCriterios");
                });

            modelBuilder.Entity("Sorteio.Domain.Familias.Familia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Familias");
                });

            modelBuilder.Entity("Sorteio.Domain.Familias.Pessoas.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Idade")
                        .HasColumnName("DataDeNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Renda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Sorteio.Domain.Familias.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CadastroValido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CadastroValido = true,
                            Descricao = "Cadastro válido"
                        },
                        new
                        {
                            Id = 2,
                            CadastroValido = false,
                            Descricao = "Já possui uma casa"
                        },
                        new
                        {
                            Id = 3,
                            CadastroValido = false,
                            Descricao = "Selecionado em outro processo de seleção"
                        },
                        new
                        {
                            Id = 4,
                            CadastroValido = false,
                            Descricao = "Cadastro incompleto"
                        });
                });

            modelBuilder.Entity("Sorteio.Domain.Criterios.ResultadoDaAvaliacaoDosCriterios", b =>
                {
                    b.HasOne("Sorteio.Domain.Familias.Familia", "Familia")
                        .WithOne()
                        .HasForeignKey("Sorteio.Domain.Criterios.ResultadoDaAvaliacaoDosCriterios", "FamiliaId");
                });

            modelBuilder.Entity("Sorteio.Domain.Familias.Pessoas.Pessoa", b =>
                {
                    b.HasOne("Sorteio.Domain.Familias.Familia", "Familia")
                        .WithMany("Pessoas")
                        .HasForeignKey("FamiliaId");
                });
#pragma warning restore 612, 618
        }
    }
}
